import type { CctvCamera } from './types';

// ── Denmark: curated public webcams ──────────────────────────────────────────
// These cameras are intentionally published by their operators for public use.
// Sources were re-verified in October 2026.
//
// A number of older Danish public webcam installations still expose plain HTTP
// JPG snapshots. CameraViewer routes those through /api/cctv/proxy so an HTTPS
// OSIRIS deployment can render them without mixed-content errors.

const DENMARK_CAMERAS: CctvCamera[] = [
  // Skagen Lystbådehavn — four official public occupancy webcams.
  // Official harbour position: 57°43.0'N 10°35.5'E.
  {
    id: 'dk-skagen-marina-1',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 1',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8080/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-2',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 2',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8081/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-3',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 3',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8088/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-4',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 4',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8090/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },

  // Nordsjællands Svæveflyveklub, Gørløse Flyveplads (EKGL).
  {
    id: 'dk-gorlose-glider-1',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Forplads',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=1&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },
  {
    id: 'dk-gorlose-glider-2',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Bane 28',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=2&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },
  {
    id: 'dk-gorlose-glider-3',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Bane 10',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=3&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },

  // Lemvig Flyveplads (EKLV).
  {
    id: 'dk-lemvig-airfield-1',
    lat: 56.503056, lng: 8.311667,
    name: 'Lemvig Flyveplads — Webcam 1',
    city: 'Lemvig', country: 'Denmark',
    feed_url: 'http://lemvig.com/webcam1/img.jpg',
    stream_type: 'jpg',
    external_url: 'http://eklv.dk/ptz%20kamera.html',
    source: 'Lemvig Flyveklub',
  },
  {
    id: 'dk-lemvig-airfield-2',
    lat: 56.503056, lng: 8.311667,
    name: 'Lemvig Flyveplads — Webcam 2',
    city: 'Lemvig', country: 'Denmark',
    feed_url: 'http://lemvig.com/webcam/img.jpg',
    stream_type: 'jpg',
    external_url: 'http://eklv.dk/ptz%20kamera.html',
    source: 'Lemvig Flyveklub',
  },

  // Svebølle Motocross Klub — three distinct public JPG channels.
  {
    id: 'dk-svebolle-mx-1',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 1',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch01.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },
  {
    id: 'dk-svebolle-mx-2',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 2',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch02.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },
  {
    id: 'dk-svebolle-mx-3',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 3',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch03.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },

  // APM Terminals Aarhus — two public live gate images.
  {
    id: 'dk-apm-aarhus-gate-1',
    lat: 56.156930, lng: 10.246820,
    name: 'APM Terminals Aarhus — Gate Area',
    city: 'Aarhus', country: 'Denmark',
    feed_url: 'https://cms-cd.apmterminals.com/apm/api/v1/gatecameras/gate-camera?id=4dbc015c-4147-4b95-b5c1-e2b3901f0478',
    stream_type: 'jpg',
    external_url: 'https://www.apmterminals.com/en/aarhus/e-tools/gate-status',
    source: 'APM Terminals Aarhus',
  },
  {
    id: 'dk-apm-aarhus-gate-2',
    lat: 56.156930, lng: 10.246820,
    name: 'APM Terminals Aarhus — Marshal Entry',
    city: 'Aarhus', country: 'Denmark',
    feed_url: 'https://cms-cd.apmterminals.com/apm/api/v1/gatecameras/gate-camera?id=66d905c7-873d-4eed-b8d6-31375f508873',
    stream_type: 'jpg',
    external_url: 'https://www.apmterminals.com/en/aarhus/e-tools/gate-status',
    source: 'APM Terminals Aarhus',
  },

  // Additional public Denmark webcams. These are intentionally exposed as
  // public webcam pages; where a stable direct media URL has not been verified,
  // OSIRIS opens the public listing rather than attempting endpoint discovery.
  {
    id: 'dk-public-store-jyndevad',
    lat: 54.897778, lng: 9.127778,
    name: 'Store Jyndevad — DMI weather webcam',
    city: 'Aabenraa', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41362-aabenraa-store-jyndevad',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aabenraa-traffic',
    lat: 55.043333, lng: 9.421111,
    name: 'Aabenraa — Traffic',
    city: 'Aabenraa', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/34859-aabenraa-traffic',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aalborg-ostre-tennis',
    lat: 57.039444, lng: 9.943611,
    name: 'Ålborg Østre Tennisklub',
    city: 'Aalborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29393-aalborg-alborg-ostre-tennisklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aalborg-tennis',
    lat: 57.053333, lng: 9.899722,
    name: 'Aalborg — Tennis courts',
    city: 'Aalborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/37833-aalborg-tennis-courts',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-marselisborghavn',
    lat: 56.138611, lng: 10.214444,
    name: 'Marselisborghavn',
    city: 'Aarhus', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/8418-aarhus-marselisborghavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aarhus-risskov',
    lat: 56.202500, lng: 10.282222,
    name: 'Aarhus — Risskov',
    city: 'Aarhus', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35318-aarhus-risskov',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-alsgarde-langebro',
    lat: 56.076111, lng: 12.546667,
    name: 'Ålsgårde — Langebro',
    city: 'Ålsgårde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29389-alsgarde-langebro',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-anholt-harbour',
    lat: 56.715556, lng: 11.514167,
    name: 'Anholt — Harbour',
    city: 'Anholt', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/31989-anholt-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-lynetteholm',
    lat: 55.688333, lng: 12.626389,
    name: 'Lynetteholm construction webcam',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/32210-copenhagen-lynetteholm',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hirtshals-harbour',
    lat: 57.592222, lng: 9.969167,
    name: 'Hirtshals — Harbour',
    city: 'Hirtshals', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/16085-hirtshals-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hvide-sande-sportsfisker',
    lat: 56.003889, lng: 8.127778,
    name: 'Hvide Sande — Sportsfisker Center',
    city: 'Hvide Sande', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/33977-hvide-sande-sportsfisker-center',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-juelsminde-marina',
    lat: 55.714167, lng: 10.015833,
    name: 'Juelsminde — Havn & Marina',
    city: 'Juelsminde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/13072-juelsminde-havn-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-henne-golf',
    lat: 55.736389, lng: 8.226389,
    name: 'Henne Golfklub',
    city: 'Henne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21026-henne-henne-golfklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-nivaa-harbour',
    lat: 55.938889, lng: 12.528611,
    name: 'Nivå — Harbour',
    city: 'Nivå', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/27077-niva-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-rungsted-marina',
    lat: 55.886111, lng: 12.545556,
    name: 'Rungsted — Marina',
    city: 'Rungsted', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21036-rungsted-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-saeby-beach',
    lat: 57.330000, lng: 10.529167,
    name: 'Sæby — Beach',
    city: 'Sæby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21020-saeby-beach',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vejle-marina',
    lat: 55.707778, lng: 9.556111,
    name: 'Vejle — Lystbådehavn',
    city: 'Vejle', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17281-vejle-lystbadehavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vorupor',
    lat: 56.958889, lng: 8.364722,
    name: 'Vorupør',
    city: 'Vorupør', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5059-vorupor',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-ronne-havn',
    lat: 55.099167, lng: 14.690833,
    name: 'Rønne Havn',
    city: 'Rønne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/523-bornholm-ronne-havn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-great-belt',
    lat: 55.333056, lng: 10.962500,
    name: 'Great Belt Fixed Link',
    city: 'Storebælt', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21031-great-belt-fixed-link',
    source: 'Public webcam listing',
  },


  // Second verified public-webcam tranche (October 2026).
  {
    id: 'dk-public-assens-toro',
    lat: 55.244167, lng: 9.888611,
    name: 'Assens — Torø',
    city: 'Assens', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41361-assens-toro',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-augustenborg-yachthavn',
    lat: 54.941944, lng: 9.871667,
    name: 'Augustenborg — Yachthavn',
    city: 'Augustenborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17278-augustenborg-yachthavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aero-soby-golf',
    lat: 54.969444, lng: 10.205278,
    name: 'Ærø — Søby — Ærø Golf Club',
    city: 'Søby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/26019-aero-island-soby-aero-golf-club',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-blavand-naturpark',
    lat: 55.557222, lng: 8.083333,
    name: 'Blåvand — Naturpark Vesterhavet',
    city: 'Blåvand', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17277-blavand-naturpark-vesterhavet',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-bornholm-vang',
    lat: 55.248611, lng: 14.736667,
    name: 'Bornholm — Vang',
    city: 'Vang', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/516-bornholm-vang',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-brejning-harbour',
    lat: 55.674722, lng: 9.690833,
    name: 'Brejning — Harbour',
    city: 'Brejning', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/37095-brejning-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-copenhagen-radhuspladsen',
    lat: 55.675556, lng: 12.568611,
    name: 'Copenhagen — Rådhuspladsen',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29398-copenhagen-radhuspladsen',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-egernsund-marina-minde',
    lat: 54.896944, lng: 9.618056,
    name: 'Egernsund — Marina Minde',
    city: 'Egernsund', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5184-egernsund-marina-minde',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-esbjerg-beach',
    lat: 55.528056, lng: 8.347500,
    name: 'Esbjerg — Beach',
    city: 'Esbjerg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35995-esbjerg-beach',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fano-nordby',
    lat: 55.448611, lng: 8.406944,
    name: 'Fanø — Nordby',
    city: 'Nordby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17275-fano-nordby',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fredericia-little-belt',
    lat: 55.519444, lng: 9.745000,
    name: 'Fredericia — Little Belt Bridge',
    city: 'Fredericia', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5185-fredericia-little-belt-bridge',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-frederikshavn-harbour',
    lat: 57.441389, lng: 10.547222,
    name: 'Frederikshavn — Harbour',
    city: 'Frederikshavn', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/24836-frederikshavn-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-gilleleje-golf',
    lat: 56.081389, lng: 12.366667,
    name: 'Gilleleje Golfklub',
    city: 'Gilleleje', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29395-gilleleje-gilleleje-golfklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-givskud-zoo',
    lat: 55.812222, lng: 9.350833,
    name: 'Givskud Zoo — Zootopia',
    city: 'Givskud', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35092-givskud-givskud-zoo-zootopia',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-gribskov-osprey',
    lat: 55.998889, lng: 12.285556,
    name: 'Gribskov — Osprey nest',
    city: 'Gribskov', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/26017-gribskov-osprey-nest',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hellerup-sejlklub',
    lat: 55.731389, lng: 12.581111,
    name: 'Hellerup Sejlklub',
    city: 'Hellerup', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/11486-hellerup-sejlklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-helsingor-oresund',
    lat: 56.048056, lng: 12.598333,
    name: 'Helsingør — Øresund',
    city: 'Helsingør', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/18737-helsingor-oresund',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hundested-harbor',
    lat: 55.963611, lng: 11.845278,
    name: 'Hundested — Harbor',
    city: 'Hundested', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/26015-hundested-harbor',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-karrebaeksminde-harbour',
    lat: 55.176389, lng: 11.647778,
    name: 'Karrebæksminde — Harbour',
    city: 'Karrebæksminde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/25939-karrebaeksminde-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-koge-marina',
    lat: 55.470278, lng: 12.196111,
    name: 'Køge — Marina',
    city: 'Køge', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29390-koge-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-oro-ostre-faerge',
    lat: 55.756944, lng: 11.835556,
    name: 'Orø — Østre Færge',
    city: 'Orø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/26016-oro-ostre-faerge',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-roskilde-marina',
    lat: 55.650833, lng: 12.076389,
    name: 'Roskilde — Marina',
    city: 'Roskilde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17284-roskilde-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-skive-flyveklub',
    lat: 56.550833, lng: 9.171111,
    name: 'Skive Flyveklub',
    city: 'Skive', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5192-skive-flyveklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-skodstrup-kalovig',
    lat: 56.244167, lng: 10.340833,
    name: 'Skødstrup — Kaløvig Havnen',
    city: 'Skødstrup', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/13964-skodstrup-kalovig-havnen',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-krusa-traffic',
    lat: 54.849444, lng: 9.402222,
    name: 'Kruså — Traffic',
    city: 'Kruså', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5193-krusa-traffic',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-sortso-strand',
    lat: 54.933333, lng: 11.980278,
    name: 'Sortsø Strand',
    city: 'Sortsø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21030-sortso-strand',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-smedager-storks',
    lat: 54.976944, lng: 9.178611,
    name: 'Smedagervej — Storks',
    city: 'Smedager', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/18237-smedagervej-storks',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-svendborg-sund',
    lat: 55.041667, lng: 10.572222,
    name: 'Svendborg — Svendborgsund',
    city: 'Svendborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29418-svendborg-svendborgsund',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-thuro-marina',
    lat: 55.042500, lng: 10.669167,
    name: 'Thurø — Marina',
    city: 'Thurø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21029-thuro-thuro-by-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-viborg-airport',
    lat: 56.410833, lng: 9.412222,
    name: 'Viborg — Airport',
    city: 'Viborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35727-viborg-airport',
    source: 'Public webcam listing',
  },

  // Third verified public-webcam tranche — expands Denmark beyond 100 map markers.
  {
    id: 'dk-public-aarhus-ega-tennis',
    lat: 56.226944, lng: 10.294444,
    name: 'Aarhus — Egå Tennis courts',
    city: 'Aarhus', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/40420-aarhus-ega-tennis-courts',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-bornholm-ronne-tv2',
    lat: 55.100556, lng: 14.695833,
    name: 'Bornholm — Rønne TV2',
    city: 'Rønne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/524-bornholm-ronne-tv2',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-copenhagen-kalveboderne',
    lat: 55.637222, lng: 12.519167,
    name: 'Copenhagen — Kalveboderne',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/28780-copenhagen-kalveboderne',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-copenhagen-kalveboderne-bay',
    lat: 55.637222, lng: 12.519444,
    name: 'Copenhagen — Kalveboderne Bay',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41356-copenhagen-kalveboderne-bay',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-copenhagen-klovermarkens',
    lat: 55.670000, lng: 12.605556,
    name: 'Copenhagen — Kløvermarkens Tennis Club',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/37097-copenhagen-klovermarkens-tennis-club',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fano-feldberg',
    lat: 55.423611, lng: 8.383611,
    name: 'Fanø — Feldberg Familie Camping',
    city: 'Fanø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35317-fano-feldberg-familie-camping',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fjenneslev-glider',
    lat: 55.451667, lng: 11.640278,
    name: 'Fjenneslev — Midtsjællands Svæveflyveklub',
    city: 'Fjenneslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/9744-fjenneslev-midtsjaellands-svaeveflyveklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fredensborg-tennis',
    lat: 55.977222, lng: 12.413056,
    name: 'Fredensborg — Tennis courts',
    city: 'Fredensborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/40421-fredensborg-tennis-courts',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-fredericia-little-belt',
    lat: 55.560556, lng: 9.767778,
    name: 'Fredericia — Little Belt',
    city: 'Fredericia', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41357-fredericia-little-belt',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-haderslev-arosund-1',
    lat: 55.262222, lng: 9.710000,
    name: 'Haderslev — Årøsund Havn 1',
    city: 'Haderslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/36650-haderslev-arosund-havn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-haderslev-arosund-2',
    lat: 55.262778, lng: 9.706944,
    name: 'Haderslev — Årøsund Havn 2',
    city: 'Haderslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/33982-haderslev-arosund-havn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-haderslev-sandersvig-deer',
    lat: 55.334444, lng: 9.631667,
    name: 'Haderslev — Sandersvig deer park',
    city: 'Haderslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/32919-haderslev-sandersvig-camping-tropeland-deer-park',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-haderslev-sandersvig',
    lat: 55.334444, lng: 9.631667,
    name: 'Haderslev — Sandersvig Camping & Tropeland',
    city: 'Haderslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/11069-haderslev-sandersvig-camping-tropeland',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hals-hou-marina',
    lat: 57.056944, lng: 10.377500,
    name: 'Hals — Hou Lystbådehavn',
    city: 'Hals', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17276-hals-hou-lystbadehavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-havndal-udbyhoj',
    lat: 56.610833, lng: 10.306944,
    name: 'Havndal — Udbyhøj Lystbådehavn',
    city: 'Havndal', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/26013-havndal-udbyhoj-lystbadehavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-havneby-list-ferry',
    lat: 55.086111, lng: 8.566667,
    name: 'Havneby — List ferry',
    city: 'Havneby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17285-havneby-list-ferry',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-helsinge-arreso',
    lat: 56.016667, lng: 12.087500,
    name: 'Helsinge — Arresø',
    city: 'Helsinge', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21034-helsinge-arreso',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-henne-beach',
    lat: 55.743889, lng: 8.173611,
    name: 'Henne — Beach',
    city: 'Henne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21252-henne-beach',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-herning-tjorring',
    lat: 56.157778, lng: 8.920556,
    name: 'Herning — Tjørring',
    city: 'Herning', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/34861-herning-tjorring',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-holbaek-airfield',
    lat: 55.734167, lng: 11.600278,
    name: 'Holbæk — Airfield',
    city: 'Holbæk', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41360-holbaek-airfield',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-holbaek-kirke-sonnerup',
    lat: 55.649722, lng: 11.813333,
    name: 'Holbæk — Kirke Sonnerup',
    city: 'Holbæk', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29415-holbaek-kirke-sonnerup',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hvide-sande-kabelpark',
    lat: 56.018611, lng: 8.130556,
    name: 'Hvide Sande — Kabelpark',
    city: 'Hvide Sande', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/19667-hvide-sande-kabelpark',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hvide-sande-lyngvig-fyr',
    lat: 56.050000, lng: 8.105556,
    name: 'Hvide Sande — Lyngvig Fyr',
    city: 'Hvide Sande', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/18266-hvide-sande-lyngvig-fyr',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-ikast-isenvad',
    lat: 56.093889, lng: 9.181111,
    name: 'Ikast-Brande — Isenvad',
    city: 'Ikast-Brande', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41358-ikast-brande-isenvad',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-kalundborg-flyveplads',
    lat: 55.700000, lng: 11.260556,
    name: 'Kalundborg — Flyveplads',
    city: 'Kalundborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5188-kalundborg-flyveplads',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-knebel-sletterhage',
    lat: 56.095278, lng: 10.513056,
    name: 'Knebel — Sletterhage Lighthouse',
    city: 'Knebel', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/27181-knebel-sletterhage-lighthouse',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-koge-golf',
    lat: 55.427222, lng: 12.175278,
    name: 'Køge — Golf course',
    city: 'Køge', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/37096-koge-golf-course',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-lihme-gyldendal',
    lat: 56.580833, lng: 8.710833,
    name: 'Lihme — Gyldendal Havn',
    city: 'Lihme', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21022-lihme-gyldendal-havn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-lojt-sandskaer',
    lat: 55.116944, lng: 9.496944,
    name: 'Løjt Kirkeby — Sandskaer Strandcamping',
    city: 'Løjt Kirkeby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21027-lojt-kirkeby-sandskaer-strandcamping',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-lokken-beach',
    lat: 57.371667, lng: 9.704444,
    name: 'Løkken — Beach',
    city: 'Løkken', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/36834-lokken-beach',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-naestved-holmegaard-mx',
    lat: 55.221389, lng: 11.896667,
    name: 'Næstved — Holmegaard Motocross',
    city: 'Næstved', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/33983-naestved-holmegaard-motocross',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-odder-hou-camping',
    lat: 55.926111, lng: 10.255000,
    name: 'Odder — Hou Strand Camping',
    city: 'Odder', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35998-odder-hou-strand-camping',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-olgod-lykkeso',
    lat: 55.809722, lng: 8.636667,
    name: 'Ølgod — LykkeSø fishing club',
    city: 'Ølgod', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/36039-olgod-lykkeso-fishing-club',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-oresund-bridge',
    lat: 55.594444, lng: 12.765278,
    name: 'Øresund Bridge',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/12212-oresund-bridge',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-padborg-motocross',
    lat: 54.871111, lng: 9.271111,
    name: 'Padborg — Vesterbæk Moto Cross Club',
    city: 'Padborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29402-padborg-vesterbaek-moto-cross-club',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-randers-airport',
    lat: 56.506111, lng: 10.036389,
    name: 'Randers — Airport',
    city: 'Randers', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5189-randers-airport',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-randers-hald',
    lat: 56.560278, lng: 10.092222,
    name: 'Randers — Hald',
    city: 'Randers', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41363-randers-hald',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-ronnede-flyveklub',
    lat: 55.250278, lng: 12.060833,
    name: 'Rønnede — Øst-Sjællands Flyveklub',
    city: 'Rønnede', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/32212-ronnede-ost-sjaellands-flyveklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-saeby-airport',
    lat: 57.345278, lng: 10.414167,
    name: 'Sæby — Airport',
    city: 'Sæby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29392-saeby-airport',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-sonderborg-motocross',
    lat: 54.918611, lng: 9.694722,
    name: 'Sønderborg — Motocross track',
    city: 'Sønderborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29414-sonderborg-motocross-track',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-svendborg-golf',
    lat: 55.088611, lng: 10.553611,
    name: 'Svendborg — Golf course',
    city: 'Svendborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/34393-svendborg-golf-course',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-torring-glider',
    lat: 55.906111, lng: 9.454444,
    name: 'Tørring — Vejle Svæveflyveklub',
    city: 'Tørring', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/9746-torring-vejle-svaeveflyveklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-ullerslev-beekeeping',
    lat: 55.362778, lng: 10.669444,
    name: 'Ullerslev — Beekeeping',
    city: 'Ullerslev', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29394-ullerslev-beekeeping',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-varde-golf',
    lat: 55.623056, lng: 8.508889,
    name: 'Varde — Golf course',
    city: 'Varde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41364-varde-golf-course',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vederso-panoramic',
    lat: 56.255556, lng: 8.132222,
    name: 'Vedersø Klitvej — Panoramic view',
    city: 'Vedersø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21024-vederso-klitvej-panoramic-view',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vestero-havn',
    lat: 57.296111, lng: 10.923611,
    name: 'Vesterø Havn, Læsø',
    city: 'Læsø', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/415-vestero-havn-laeso',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vindebaek-tolkedyb',
    lat: 54.879167, lng: 12.184167,
    name: 'Vindebæk — Tolkedyb',
    city: 'Vindebæk', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41359-vindebaek-tolkedyb',
    source: 'Public webcam listing',
  },

];

export async function fetchDenmarkCameras(): Promise<CctvCamera[]> {
  return DENMARK_CAMERAS;
}
