import type { CctvCamera } from './types';

// ── Denmark: curated public webcams ──────────────────────────────────────────
// These cameras are intentionally published by their operators for public use.
// Sources were re-verified in October 2026.
//
// A number of older Danish public webcam installations still expose plain HTTP
// JPG snapshots. CameraViewer routes those through /api/cctv/proxy so an HTTPS
// OSIRIS deployment can render them without mixed-content errors.

const DENMARK_CAMERAS: CctvCamera[] = [
  // Skagen Lystbådehavn — four official public occupancy webcams.
  // Official harbour position: 57°43.0'N 10°35.5'E.
  {
    id: 'dk-skagen-marina-1',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 1',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8080/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-2',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 2',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8081/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-3',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 3',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8088/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },
  {
    id: 'dk-skagen-marina-4',
    lat: 57.716667, lng: 10.591667,
    name: 'Skagen Lystbådehavn — Webcam 4',
    city: 'Skagen', country: 'Denmark',
    feed_url: 'http://87.56.55.165:8090/snapshot.cgi',
    stream_type: 'jpg',
    external_url: 'https://skagenlystbaadehavn.frederikshavn.dk/webcams',
    source: 'Skagen Lystbådehavn',
  },

  // Nordsjællands Svæveflyveklub, Gørløse Flyveplads (EKGL).
  {
    id: 'dk-gorlose-glider-1',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Forplads',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=1&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },
  {
    id: 'dk-gorlose-glider-2',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Bane 28',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=2&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },
  {
    id: 'dk-gorlose-glider-3',
    lat: 55.885000, lng: 12.229167,
    name: 'Gørløse Flyveplads — Bane 10',
    city: 'Gørløse', country: 'Denmark',
    feed_url: 'http://glider.dk/sites/all/modules/customNSFmodules/webcam_image.php?cam=3&sz=s&d=0',
    stream_type: 'jpg',
    external_url: 'http://glider.dk/webcam',
    source: 'Nordsjællands Svæveflyveklub',
  },

  // Lemvig Flyveplads (EKLV).
  {
    id: 'dk-lemvig-airfield-1',
    lat: 56.503056, lng: 8.311667,
    name: 'Lemvig Flyveplads — Webcam 1',
    city: 'Lemvig', country: 'Denmark',
    feed_url: 'http://lemvig.com/webcam1/img.jpg',
    stream_type: 'jpg',
    external_url: 'http://eklv.dk/ptz%20kamera.html',
    source: 'Lemvig Flyveklub',
  },
  {
    id: 'dk-lemvig-airfield-2',
    lat: 56.503056, lng: 8.311667,
    name: 'Lemvig Flyveplads — Webcam 2',
    city: 'Lemvig', country: 'Denmark',
    feed_url: 'http://lemvig.com/webcam/img.jpg',
    stream_type: 'jpg',
    external_url: 'http://eklv.dk/ptz%20kamera.html',
    source: 'Lemvig Flyveklub',
  },

  // Svebølle Motocross Klub — three distinct public JPG channels.
  {
    id: 'dk-svebolle-mx-1',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 1',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch01.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },
  {
    id: 'dk-svebolle-mx-2',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 2',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch02.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },
  {
    id: 'dk-svebolle-mx-3',
    lat: 55.667194, lng: 11.305500,
    name: 'Svebølle Motocross — Kamera 3',
    city: 'Svebølle', country: 'Denmark',
    feed_url: 'https://smck.dk/webcam/ch03.jpg',
    stream_type: 'jpg',
    external_url: 'https://smck.dk/webcam',
    source: 'Svebølle Motocross Klub',
  },

  // APM Terminals Aarhus — two public live gate images.
  {
    id: 'dk-apm-aarhus-gate-1',
    lat: 56.156930, lng: 10.246820,
    name: 'APM Terminals Aarhus — Gate Area',
    city: 'Aarhus', country: 'Denmark',
    feed_url: 'https://cms-cd.apmterminals.com/apm/api/v1/gatecameras/gate-camera?id=4dbc015c-4147-4b95-b5c1-e2b3901f0478',
    stream_type: 'jpg',
    external_url: 'https://www.apmterminals.com/en/aarhus/e-tools/gate-status',
    source: 'APM Terminals Aarhus',
  },
  {
    id: 'dk-apm-aarhus-gate-2',
    lat: 56.156930, lng: 10.246820,
    name: 'APM Terminals Aarhus — Marshal Entry',
    city: 'Aarhus', country: 'Denmark',
    feed_url: 'https://cms-cd.apmterminals.com/apm/api/v1/gatecameras/gate-camera?id=66d905c7-873d-4eed-b8d6-31375f508873',
    stream_type: 'jpg',
    external_url: 'https://www.apmterminals.com/en/aarhus/e-tools/gate-status',
    source: 'APM Terminals Aarhus',
  },

  // Additional public Denmark webcams. These are intentionally exposed as
  // public webcam pages; where a stable direct media URL has not been verified,
  // OSIRIS opens the public listing rather than attempting endpoint discovery.
  {
    id: 'dk-public-store-jyndevad',
    lat: 54.897778, lng: 9.127778,
    name: 'Store Jyndevad — DMI weather webcam',
    city: 'Aabenraa', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/41362-aabenraa-store-jyndevad',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aabenraa-traffic',
    lat: 55.043333, lng: 9.421111,
    name: 'Aabenraa — Traffic',
    city: 'Aabenraa', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/34859-aabenraa-traffic',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aalborg-ostre-tennis',
    lat: 57.039444, lng: 9.943611,
    name: 'Ålborg Østre Tennisklub',
    city: 'Aalborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29393-aalborg-alborg-ostre-tennisklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aalborg-tennis',
    lat: 57.053333, lng: 9.899722,
    name: 'Aalborg — Tennis courts',
    city: 'Aalborg', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/37833-aalborg-tennis-courts',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-marselisborghavn',
    lat: 56.138611, lng: 10.214444,
    name: 'Marselisborghavn',
    city: 'Aarhus', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/8418-aarhus-marselisborghavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-aarhus-risskov',
    lat: 56.202500, lng: 10.282222,
    name: 'Aarhus — Risskov',
    city: 'Aarhus', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/35318-aarhus-risskov',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-alsgarde-langebro',
    lat: 56.076111, lng: 12.546667,
    name: 'Ålsgårde — Langebro',
    city: 'Ålsgårde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/29389-alsgarde-langebro',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-anholt-harbour',
    lat: 56.715556, lng: 11.514167,
    name: 'Anholt — Harbour',
    city: 'Anholt', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/31989-anholt-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-lynetteholm',
    lat: 55.688333, lng: 12.626389,
    name: 'Lynetteholm construction webcam',
    city: 'Copenhagen', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/32210-copenhagen-lynetteholm',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hirtshals-harbour',
    lat: 57.592222, lng: 9.969167,
    name: 'Hirtshals — Harbour',
    city: 'Hirtshals', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/16085-hirtshals-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-hvide-sande-sportsfisker',
    lat: 56.003889, lng: 8.127778,
    name: 'Hvide Sande — Sportsfisker Center',
    city: 'Hvide Sande', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/33977-hvide-sande-sportsfisker-center',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-juelsminde-marina',
    lat: 55.714167, lng: 10.015833,
    name: 'Juelsminde — Havn & Marina',
    city: 'Juelsminde', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/13072-juelsminde-havn-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-henne-golf',
    lat: 55.736389, lng: 8.226389,
    name: 'Henne Golfklub',
    city: 'Henne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21026-henne-henne-golfklub',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-nivaa-harbour',
    lat: 55.938889, lng: 12.528611,
    name: 'Nivå — Harbour',
    city: 'Nivå', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/27077-niva-harbour',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-rungsted-marina',
    lat: 55.886111, lng: 12.545556,
    name: 'Rungsted — Marina',
    city: 'Rungsted', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21036-rungsted-marina',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-saeby-beach',
    lat: 57.330000, lng: 10.529167,
    name: 'Sæby — Beach',
    city: 'Sæby', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21020-saeby-beach',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vejle-marina',
    lat: 55.707778, lng: 9.556111,
    name: 'Vejle — Lystbådehavn',
    city: 'Vejle', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/17281-vejle-lystbadehavn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-vorupor',
    lat: 56.958889, lng: 8.364722,
    name: 'Vorupør',
    city: 'Vorupør', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/5059-vorupor',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-ronne-havn',
    lat: 55.099167, lng: 14.690833,
    name: 'Rønne Havn',
    city: 'Rønne', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/523-bornholm-ronne-havn',
    source: 'Public webcam listing',
  },
  {
    id: 'dk-public-great-belt',
    lat: 55.333056, lng: 10.962500,
    name: 'Great Belt Fixed Link',
    city: 'Storebælt', country: 'Denmark',
    external_url: 'https://worldcam.eu/webcams/europe/denmark/21031-great-belt-fixed-link',
    source: 'Public webcam listing',
  },

];

export async function fetchDenmarkCameras(): Promise<CctvCamera[]> {
  return DENMARK_CAMERAS;
}
